#关闭模板引擎的缓冲
spring:
#国际化配置
  messages:
#指定国际化配置文件位置
    basename: i18n.login
  thymeleaf:
    cache: false
#设置时间转换格式
  mvc:
    format:
      date: yyyy-MM-dd
#修改项目虚拟目录
#server:
#  servlet:
#    context-path: "/ye"
